# Generated by Django 5.0 on 2023-12-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0004_remove_pedido_ciclo"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="bairro",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="cep",
            field=models.CharField(default=0, max_length=10, verbose_name="CEP"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="cidade",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="logradouro",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="numero",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Número"
            ),
        ),
    ]
